spring.application.name=billsoft
spring.datasource.url=jdbc:h2:file:~/.billsoft/database;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
app.version=v1.0.0

# Fix Hibernate lazy loading serialization issues
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true