spring.application.name=billsoft
spring.datasource.url=jdbc:mysql://localhost:3306/Invoicemaker
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
app.version=v1.0.0
